### ISSUE TITLE
FlappyBlazorBird.BlazorHosted is missing wwwroot

### ISSUE THREAD

**Issue by dfyx** [ctrl-alt-d/FlappyBlazorBird#5]
When I build the wasm version, all images are missing. When I copy over the wwwroot folder from one of the other projects in the solution, everything works as expected.

**Comment by ctrl-alt-d** [comment]
Danke vielmals @dfyx . Ich habe vergessen, die CSS-Datei zu aktualisieren, wenn ich Bilder als Div-Hintergrund festgelegt habe.  (translated with Google trans ... I hope text has sense for you ;)

**Comment by dfyx** [comment]
That translation is surprisingly accurate.
